spring:
  application:
    name: user-service

  profiles:
    active: local

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: user_db

  jpa:
    properties:
      hibernate:
        default_schema: user_db

server:
  port: 9002

invoice:
    service:
        url: http://localhost:9001