CREATE TABLE invoice_db.INVOICE (
    INVOICE_ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    INVOICE_NUMBER VARCHAR(255) NOT NULL,
    PRODUCT_IDS TEXT NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    constraint PK_INVOICE_ID PRIMARY KEY (INVOICE_ID)
);